### ISSUE TITLE
How to prune?

### ISSUE THREAD

**Issue by SamK** [apollo13/ansible-role-borgbackup#10]
Hi,

I am wondering how/where to execute the `borg prune` command with this role.

Any idea or suggestion?

Thank you.

**Comment by apollo13** [comment]
Mhm I guess I didn't implement it since I usually prune from a dedicated host with an admin SSH key. Ie my backups are usually append only. PRs welcome :)

**Comment by SamK** [comment]
Thanks.

I'll see what I can do.

Cheers.
