### ISSUE TITLE
Who is borgbackup_user?

### ISSUE THREAD

**Issue by indibart** [apollo13/ansible-role-borgbackup#4]
Hi apollo
I found a bit of time to give your borgbackup-role an other try. Unfortunately I'm still struggling a bit. In particular I don't understand the variable `borgbackup_user`. Can you help me? I'll try to explain what I'm having in mind to achieve:

A laptop belonging to Alice (sudo) and with Bob as a second account (non-sudo).
I would like to backup Alices and Bobs home-folders to my backup-server.

I thougt that in this scenario `borgbackup_user` is `alice`, so `borgbackup_home` is `/home/alice`. `borgbackup_directories` which will be backed up to the backup-server I define as `/home/alice` and `/home/bob`.
On the backup-server there is a user called `borg` which writes on `borgbackup_repository_storage` which I can define as `/home/borg`. So then `borg` creates the folders `/home/borg/home/alice` and `/home/borg/home/bob` on the backup-server.

So I configured my variables as follows:
```
borgbackup_user: "alice"
borgbackup_directories:
   - "{{  borgbackup_home  }}"
   - "/home/bob"
borgbackup_repository_storage: "/home/borg"
```

Is that the right way to do it?

Thanks for your help!

**Comment by apollo13** [comment]
> I thougt that in this scenario borgbackup_user is alice, so borgbackup_home is /home/alice. borgbackup_directories which will be backed up to the backup-server I define as /home/alice and /home/bob.

Generally if you backup multiple users it makes sense to set `borgbackup_user` to `root` -- it is the user under which borgbackup is run from systemd. (Make sure to set `borgbackup_home` to something sensible then).

> So then borg creates the folders /home/borg/home/alice and /home/borg/home/bob on the backup-server.

Not that's not how the upload works, it will just create one folder with the inventory name of your laptop.

**Comment by indibart** [comment]
> Generally if you backup multiple users it makes sense to set borgbackup_user to root -- it is the user under which borgbackup is run from systemd.

Okay, thanks.
Edit: So what would then be a situation when I wouldn't use `root` as `borgbackup_user`? Why wouldn't that also make sense when I'm only backing up a single user?

> (Make sure to set borgbackup_home to something sensible then).

What do you mean? Don't I just then have to define the `borgbackup_directories` without `borgbackup_home` (which then would be `/root/borg`). Like so:

```
borgbackup_user: "root"
borgbackup_directories:
   - "/home/alice"
   - "/home/bob"
borgbackup_repository_storage: "/home/borg"
```

**Comment by apollo13** [comment]
> Don't I just then have to define the borgbackup_directories without borgbackup_home (which then would be /root/borg).

Correct, this was a mistake on my side, wasn't sure if the role properly constructs /root then…

>  Edit: So what would then be a situation when I wouldn't use root as borgbackup_user? Why wouldn't that also make sense when I'm only backing up a single user?

For security reasons you generally do not want to run as root, hence this role by default runs as normal user + the rights to read all content via CAP_DAC_READ_SEARCH, though I probably should disable this by default

**Comment by indibart** [comment]
> For security reasons you generally do not want to run as root, hence this role by default runs as normal user + the rights to read all content via CAP_DAC_READ_SEARCH, though I probably should disable this by default

I'm not sure I understand you... What should you disable? The use of `root`?
So then my scenario of using the user `alice` which isn't root but has sudo-rights is better?
Or would it be best to add a normal (system) user `borg` on the laptop which gets only the read-rights from the role?

**Comment by apollo13** [comment]
> I'm not sure I understand you... What should you disable? The use of root?

The `CAP_DAC_READ_SEARCH` capabiility

>  So then my scenario of using the user alice which isn't root but has sudo-rights is better?

Having sudo rights doesn't matter, the systemd service ensures that your user can read everything: https://github.com/apollo13/ansible-role-borgbackup/blob/master/templates/borgbackup.service.j2#L14

> Or would it be best to add a normal (system) user borg on the laptop which gets only the read-rights from the role?

Yes, that would be my recommendation. Just be aware that I will add an option that turns `CAP_DAC_READ_SEARCH` on & off in a further release and it will default to off (so you'd then have to explicitly enable it)

**Comment by apollo13** [comment]
Hi, I am closing this now, if you have further questions feel free to open a new ticket.
