### ISSUE TITLE
Simplify variables problem

### ISSUE THREAD

**Issue by Punkado** [apollo13/ansible-role-borgbackup#8]
Hello,

I am having a problem, the configure_server.yml is not seeing my the variable borgbackup_repository_storage, even thought that i set it up every where i could, in the playbook and host_vars/server.yml.

The error message is:

`
TASK [apollo13.borgbackup : Simplify variables 2/2] **********************************************************************************************************
fatal: [borg-test]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'borgbackup_repository_storage'\n\nThe error appears to be in '/home/roberto/Nextcloud/work/ansible/roles/apollo13.borgbackup/tasks/configure_server.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Simplify variables 2/2\n  ^ here\n"}
` 

My playbook:

- hosts: borg-server
  vars:
    borgbackup_repository_storage: /home/borgbackup
  roles:
    - apollo13.borgbackup

- hosts: borg-test
  vars:
    borgbackup_passphrase: password
    borgbackup_directories: /home
    borgbackup_repository_server: borg-server
  roles:
    - apollo13.borgbackup

Thanks

**Comment by apollo13** [comment]
Hi, can you please try setting the variable as host variable (a group variable should probably also work)? This is certainly something I did not consider :(

**Comment by Punkado** [comment]
It worked, thanks...

Some variable need to defined in the hosts inventory, cant be in the playbook.
